### ISSUE TITLE
Missing .exe in the zip folder

### ISSUE THREAD

**Issue by orangepeelsss** [Miclebrick/Schematic2Json#3]
Once you download and extract the .zip file, the .exe file is not in any of the folders.
![image](https://user-images.githubusercontent.com/69936857/104525717-0589db80-55be-11eb-8bf3-8ca57ff2c5bc.png)
![image](https://user-images.githubusercontent.com/69936857/104525722-0a4e8f80-55be-11eb-9733-eb45cf1fc0b4.png)
![image](https://user-images.githubusercontent.com/69936857/104525733-0e7aad00-55be-11eb-93d5-55a5a0a41978.png)

**Comment by hafarooki** [comment]
You are downloading the wrong file, download the release, not the source code zip. Latest release from 2016 is here https://github.com/Miclebrick/Schematic2Json/files/505273/Schematic2Json.v0.0.7.zip
